services:
  client:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      go-network:
        ipv4_address: 192.168.150.10
        aliases:
          - lb
  goapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      go-network:
        ipv4_address: 192.168.151.10
        aliases:
          - goapp
    secrets:
      - db-password
    
  db:
    image: mysql:9.4.0-oracle
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      go-network:
        ipv4_address: 192.168.152.10
        aliases:
          - db

networks:
  go-network:
    # external: true  
    driver: ipvlan
    driver_opts:
      parent: wlp61s0
      ipvlan_mode: l3
      ipvlan_flag: bridge
    ipam:
      config:
        - subnet: 192.168.150.0/24
        - subnet: 192.168.151.0/24
        - subnet: 192.168.152.0/24

  # db-network:
  #   driver: ipvlan
  #   driver_opts:
  #     parent: ens33
  #     ipvlan_mode: l3
  #     ipvlan_flag: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.100.0/24
  #       - subnet: 192.168.101.0/24
  #       - subnet: 192.168.102.0/24

  # lb-network:
  #   driver: ipvlan
  #   driver_opts:
  #     parent: ens33
  #     ipvlan_mode: l3
  #     ipvlan_flag: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.100.0/24
  #       - subnet: 192.168.101.0/24
  #       - subnet: 192.168.102.0/24
volumes:
  db-data:
secrets:
  db-password:
    file: ./backend/db-password

