apiVersion: v1
data:
  init.sql: |-
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'SuperSecureP@ssw0rd';
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: goapp
