apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      automountServiceAccountToken: false 
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-mysql
      - name: db-password
        secret:
          secretName: db-password
      - name: initdb
        configMap:
          name: mysql-initdb
      containers:
      - image: mysql:9.4.0-oracle
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/secrets/db-password
          - name: MYSQL_DATABASE
            value: example
        volumeMounts:
        - name: pvc
          mountPath: /var/lib/mysql
        - name: db-password
          mountPath: /run/secrets
          readOnly: true
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
        resources:
          limits:
            memory: 0.5Gi
            cpu: 500m
          requests:
            memory: 0.5Gi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: goapp
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
status:
  loadBalancer: {}
